# https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "./crates/schema/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]

[migrations_directory]
# dir = "./crates/schema/migrations"
dir = "./migrations"
